name = "anyrouter-sign"
main = "src/index.js"
compatibility_date = "2026-01-13"

[triggers]
crons = [
  "0 2 * * MON-FRI",   # 北京时间 周一~周五 10:00
  "0 11 * * SAT,SUN"   # 北京时间 周六/周日 19:00
]

# 关键：避免部署时清空你在 Dashboard 配的 vars
keep_vars = true

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
